classDiagram
    class Empresa {
        +string nombre
        +BuscarEspectaculo()
        +GenerarReportes()
        }
    
    class Espectaculo {
        +string nombre
        +string artista
        +date fecha
        +time horainicio
        +time horafin
        +string lugar
        +string descripcion 
        +string direccionLugar
        +consultarDisponibilidad()
    }

    class Sector {
        +string nombre_sector
        +string direccion
        +string UbicaciondeCadaSector
        +string  descripcion
        +string leyenda
        +int capacidadTotal
        +int capacidadDisponible
        +int Cantidad_Entradas


    }

    class Tipo_Sector {
        +float precioBase
        +Time horarioacceso
        
    }

    class Entrada {
        +int numeroEntrada
        +DateTime fechaHoraEmision
        +float importeFinal
        +string codigoQR
        +imprimirEntrada()
    }

    class Tipo_Entrada {
        +string descripcion
        +float porcentajeDescuento
        +float precioFinal
    }

    class ReporteRecaudado {
        +int cantidadVendida
        +float montoTotalFacturado
        +imprimirReporte()
        +GuardarPDF()
        +enviarEmail()
    }

    Empresa --> "1..*" Espectaculo
    Espectaculo --> "1..*" Sector
    Sector --> "1" Tipo_Sector
    Sector --> "1..*" Entrada
    Entrada --> "1" Tipo_Entrada
    Espectaculo --> "1..*" ReporteRecaudado
    